url=https://ibwaxbmvshovpenseudo.supabase.co
key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlid2F4Ym12c2hvdnBlbnNldWRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjAyOTYwODcsImV4cCI6MjAzNTg3MjA4N30.JscamGVY5aelK46xEb5P7N_ceip1_bJptZgLbcnX22Y

vercel --build-env NEXT_PUBLIC_SUPABASE_URL=$url --build-env NEXT_PUBLIC_SUPABASE_ANON_KEY=$key
